# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hn < Formula
  desc "Agent-friendly Hacker News CLI via the Algolia API"
  homepage "https://github.com/voska/hn-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/voska/hn-cli/releases/download/v0.1.0/hn-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "5aef368562ea598c304d774f26f8c8b85e2dd446c5ac51766965a2c19f088278"

      define_method(:install) do
        bin.install "hn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/voska/hn-cli/releases/download/v0.1.0/hn-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "f142e405cc1a486a449ee2ad208f4e9ad2a24b437f33d4794735081657ceb2e6"

      define_method(:install) do
        bin.install "hn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/hn-cli/releases/download/v0.1.0/hn-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "7224a99f32bab6ce4506efd26745cde2d4bc31c141e14a6bab7496c3abe50d3f"
      define_method(:install) do
        bin.install "hn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/hn-cli/releases/download/v0.1.0/hn-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "ef638ac31bc42aa7380aea6549df9c7f281e1d518d40cf1dd0cbf6728507ccf1"
      define_method(:install) do
        bin.install "hn"
      end
    end
  end

  test do
    system "#{bin}/hn", "version"
  end
end
