# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loby < Formula
  desc "Canonical CLI for Lob — direct mail, address verification, and campaigns for humans and AI agents."
  homepage "https://lobycli.com"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/voska/loby/releases/download/v0.1.6/loby_0.1.6_Darwin_x86_64.tar.gz"
      sha256 "35403a5117e79555be8c8a674f2996e39d7133f35953400c6e0013c10ffc933a"

      define_method(:install) do
        bin.install "loby"
        generate_completions_from_executable(bin/"loby", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/voska/loby/releases/download/v0.1.6/loby_0.1.6_Darwin_arm64.tar.gz"
      sha256 "22cc5f04970c4e357a6142f7340d719a1653ce21f18a8371d387c9a8751fe413"

      define_method(:install) do
        bin.install "loby"
        generate_completions_from_executable(bin/"loby", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/loby/releases/download/v0.1.6/loby_0.1.6_Linux_x86_64.tar.gz"
      sha256 "b75fee570bde31c077701c96da4b801475cb247f98a63c110ad75b2a0a4d5e8b"
      define_method(:install) do
        bin.install "loby"
        generate_completions_from_executable(bin/"loby", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/loby/releases/download/v0.1.6/loby_0.1.6_Linux_arm64.tar.gz"
      sha256 "72d59cf924dd7db8154dafbd2e9e39e714151f227b377e2eb900899e9350b58a"
      define_method(:install) do
        bin.install "loby"
        generate_completions_from_executable(bin/"loby", "completion")
      end
    end
  end

  test do
    assert_match "loby", shell_output("#{bin}/loby version")
  end
end
