# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loby < Formula
  desc "Canonical CLI for Lob — direct mail, address verification, and campaigns for humans and AI agents."
  homepage "https://lobycli.com"
  version "0.1.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/voska/loby/releases/download/v0.1.8/loby_0.1.8_Darwin_x86_64.tar.gz"
      sha256 "2cad23aa11b1fc70c22803790c484c99ff50582d58e3a1305cdbb053bf37cd3b"

      define_method(:install) do
        bin.install "loby"
        generate_completions_from_executable(bin/"loby", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/voska/loby/releases/download/v0.1.8/loby_0.1.8_Darwin_arm64.tar.gz"
      sha256 "19332a5b5ed0ae019056f80af1528a1be4713cb69f05dd404ce154df50cb3ff7"

      define_method(:install) do
        bin.install "loby"
        generate_completions_from_executable(bin/"loby", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/loby/releases/download/v0.1.8/loby_0.1.8_Linux_x86_64.tar.gz"
      sha256 "50bc491d2a8c37877e038e62c33894b243f34451e12433d715ce002e60eb2466"
      define_method(:install) do
        bin.install "loby"
        generate_completions_from_executable(bin/"loby", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/loby/releases/download/v0.1.8/loby_0.1.8_Linux_arm64.tar.gz"
      sha256 "d4b811aa233fbb49cb6bf3be4529b69c88984441bf9e1e776d75df162998d8bc"
      define_method(:install) do
        bin.install "loby"
        generate_completions_from_executable(bin/"loby", "completion")
      end
    end
  end

  test do
    assert_match "loby", shell_output("#{bin}/loby version")
  end
end
