# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qbo < Formula
  desc "QuickBooks Online CLI for humans and AI agents"
  homepage "https://github.com/voska/qbo-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/voska/qbo-cli/releases/download/v0.1.0/qbo-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "0af600a884bb9e34349e0062636d949063970958f4993e87593525e507b69400"

      define_method(:install) do
        bin.install "qbo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/voska/qbo-cli/releases/download/v0.1.0/qbo-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "9ad433afe6e42ea9b3a7cc9ff6bce81ed426b3767cc039bba5ab2c7f997dee3a"

      define_method(:install) do
        bin.install "qbo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/qbo-cli/releases/download/v0.1.0/qbo-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "d91a88845474b18d0127ddb8926ab6b9ede81cf0e28eb73770f05686e7da53a5"
      define_method(:install) do
        bin.install "qbo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/qbo-cli/releases/download/v0.1.0/qbo-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "441aef41eaa6908c0c8fd564f864e7e8f5340f719d0132822eb1b9d31f46ca45"
      define_method(:install) do
        bin.install "qbo"
      end
    end
  end

  test do
    system "#{bin}/qbo", "exit-codes", "--json"
  end
end
