# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qbo < Formula
  desc "QuickBooks Online CLI for humans and AI agents"
  homepage "https://github.com/voska/qbo-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/voska/qbo-cli/releases/download/v0.2.0/qbo-cli_0.2.0_darwin_amd64.tar.gz"
      sha256 "8d364fb91b7b9da443e43c1f93532c3851c08aff001e478e427ed4b82f7b5240"

      define_method(:install) do
        bin.install "qbo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/voska/qbo-cli/releases/download/v0.2.0/qbo-cli_0.2.0_darwin_arm64.tar.gz"
      sha256 "4c548c7edbfdf71459fb7b4f18adc68bb4ea0b6fed1364365d52c229319ced8d"

      define_method(:install) do
        bin.install "qbo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/qbo-cli/releases/download/v0.2.0/qbo-cli_0.2.0_linux_amd64.tar.gz"
      sha256 "468f5d99b0900a21aa43dec903c326e90697c473110a327805144e6deb99a92e"
      define_method(:install) do
        bin.install "qbo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/qbo-cli/releases/download/v0.2.0/qbo-cli_0.2.0_linux_arm64.tar.gz"
      sha256 "10a0f277983ed67df684ce150d9f068bfc3ae6ad567aa2e07f5a8086a3bd9b25"
      define_method(:install) do
        bin.install "qbo"
      end
    end
  end

  test do
    system "#{bin}/qbo", "exit-codes", "--json"
  end
end
