# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qbo < Formula
  desc "QuickBooks Online CLI for humans and AI agents"
  homepage "https://github.com/voska/qbo-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/voska/qbo-cli/releases/download/v0.2.0/qbo-cli_0.2.0_darwin_amd64.tar.gz"
      sha256 "3a103648a7a6c671be8f0de6d1dbc9ef0c4ec4e79099768b24510ce8b2ca4a23"

      define_method(:install) do
        bin.install "qbo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/voska/qbo-cli/releases/download/v0.2.0/qbo-cli_0.2.0_darwin_arm64.tar.gz"
      sha256 "3eb94fa9d3499259d31df6de9ddf682e0c792dd832bf5682a41ee20a0e8add53"

      define_method(:install) do
        bin.install "qbo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/qbo-cli/releases/download/v0.2.0/qbo-cli_0.2.0_linux_amd64.tar.gz"
      sha256 "553770c674a79449f4f7e3f947321e5ea4c3b8e0098458793944068ff742f753"
      define_method(:install) do
        bin.install "qbo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/qbo-cli/releases/download/v0.2.0/qbo-cli_0.2.0_linux_arm64.tar.gz"
      sha256 "e637c0d5e7053f0b7466d8db3a72ca727e804ba8d191c8152b7774c61951dded"
      define_method(:install) do
        bin.install "qbo"
      end
    end
  end

  test do
    system "#{bin}/qbo", "exit-codes", "--json"
  end
end
