# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toktap < Formula
  desc "Transparent proxy that taps LLM API traffic to extract token usage metrics"
  homepage "https://github.com/voska/toktap"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/voska/toktap/releases/download/v0.3.0/toktap_0.3.0_darwin_amd64.tar.gz"
      sha256 "aaeee7d018089c0475a385973c57fd289a9c6d08d04bec066a4d94a4e977dd7b"

      define_method(:install) do
        bin.install "toktap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/voska/toktap/releases/download/v0.3.0/toktap_0.3.0_darwin_arm64.tar.gz"
      sha256 "b266221331bffe25b846c47aac0cb886dc95446bab1312c8ac6f5bf7f24c69d2"

      define_method(:install) do
        bin.install "toktap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/toktap/releases/download/v0.3.0/toktap_0.3.0_linux_amd64.tar.gz"
      sha256 "c40694b7dd91fcba0707d33e2703b165cc41377121e572847cffe240e4984c87"
      define_method(:install) do
        bin.install "toktap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/toktap/releases/download/v0.3.0/toktap_0.3.0_linux_arm64.tar.gz"
      sha256 "912a7847a688c1088dcbcd3e0104007da2713132f2a03d0496dd25b14302ed7e"
      define_method(:install) do
        bin.install "toktap"
      end
    end
  end

  test do
    system "#{bin}/toktap", "--version"
  end
end
