# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zonasul < Formula
  desc "Zona Sul supermarket CLI for AI agents"
  homepage "https://github.com/voska/zonasul"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/voska/zonasul/releases/download/v0.2.0/zonasul_0.2.0_darwin_amd64.tar.gz"
      sha256 "f2afb4f32ed39efe758dfc802b6c344a7e0b57da5dbbe63e234d12736f3c1682"

      define_method(:install) do
        bin.install "zonasul"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/voska/zonasul/releases/download/v0.2.0/zonasul_0.2.0_darwin_arm64.tar.gz"
      sha256 "9357cd33c60d85d589f7068e90d69bd55abdc1dc983d64fbbde294c3edc43b30"

      define_method(:install) do
        bin.install "zonasul"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/zonasul/releases/download/v0.2.0/zonasul_0.2.0_linux_amd64.tar.gz"
      sha256 "2aef35f209e447332876fd1beb189b3c9a6f905eff612f1e1743d0f706f5f5f4"
      define_method(:install) do
        bin.install "zonasul"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/zonasul/releases/download/v0.2.0/zonasul_0.2.0_linux_arm64.tar.gz"
      sha256 "d42d6154aa429ecc559564e40b9cf234e95681ba5a5b9af75c7658f5530aa6ff"
      define_method(:install) do
        bin.install "zonasul"
      end
    end
  end

  test do
    system "#{bin}/zonasul", "agent", "exit-codes", "--json"
  end
end
