# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zonasul < Formula
  desc "Zona Sul supermarket CLI for AI agents"
  homepage "https://github.com/voska/zonasul"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/voska/zonasul/releases/download/v0.4.1/zonasul_0.4.1_darwin_amd64.tar.gz"
      sha256 "d2330a538b1885305bfcbfbe8487fbe59aea236598f8d808f0f363cf9ae06596"

      define_method(:install) do
        bin.install "zonasul"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/voska/zonasul/releases/download/v0.4.1/zonasul_0.4.1_darwin_arm64.tar.gz"
      sha256 "f78876bd88335621c031fa82dcf7d2c07111f39404bdb9def33f52c07e47ee01"

      define_method(:install) do
        bin.install "zonasul"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/zonasul/releases/download/v0.4.1/zonasul_0.4.1_linux_amd64.tar.gz"
      sha256 "d31ff8e0dee0886c1659ecc2bc1bed49129a6e3b88b55f794a880e4d3b43a03d"
      define_method(:install) do
        bin.install "zonasul"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/zonasul/releases/download/v0.4.1/zonasul_0.4.1_linux_arm64.tar.gz"
      sha256 "df7fdf654d0b826c906efbcefd8ac01703c9e87f432b9bf080ec7d551f3948c8"
      define_method(:install) do
        bin.install "zonasul"
      end
    end
  end

  test do
    system "#{bin}/zonasul", "agent", "exit-codes", "--json"
  end
end
