# This file was generated by GoReleaser. DO NOT EDIT.
cask "amadeus" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "621aed0943ad4d9ba3a6ba3c572a820c4d1e5eec3d2c9720608e6c10b8c0f784"
      url "https://github.com/voska/amadeus-cli/releases/download/v#{version}/amadeus_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/voska/amadeus-cli"
    end
    on_arm do
      sha256 "8dd956f637d490c6c05644ec1930e4f970c2b3f474bd1b827c9ebcef946ca519"
      url "https://github.com/voska/amadeus-cli/releases/download/v#{version}/amadeus_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/voska/amadeus-cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "2c7a3bf38c7c1cfb4c2f355eeb7902ad64e7331f5db9b8ed2b6c170c3b7e458c"
      url "https://github.com/voska/amadeus-cli/releases/download/v#{version}/amadeus_#{version}_linux_amd64.tar.gz",
        verified: "github.com/voska/amadeus-cli"
    end
    on_arm do
      sha256 "d8ae5ee243a9c5bab73e8b228da57717ec52f565c5aafe33890b16a7833cb5d2"
      url "https://github.com/voska/amadeus-cli/releases/download/v#{version}/amadeus_#{version}_linux_arm64.tar.gz",
        verified: "github.com/voska/amadeus-cli"
    end
  end

  name "amadeus"
  desc "Amadeus Travel API CLI for humans and AI agents"
  homepage "https://github.com/voska/amadeus-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "amadeus"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/amadeus"]
    end
  end

  # No zap stanza required

end
