# This file was generated by GoReleaser. DO NOT EDIT.
cask "frescatto" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "c410e3b1c388e8bd012e10a19b2e785774bd0d2308c3e12972570517604f507a"
      url "https://github.com/voska/frescatto/releases/download/v#{version}/frescatto_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/voska/frescatto"
    end
    on_arm do
      sha256 "96ca699b8acbd4902741efd53b16733847bd24c423f4bd061236e70b90e66398"
      url "https://github.com/voska/frescatto/releases/download/v#{version}/frescatto_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/voska/frescatto"
    end
  end

  on_linux do
    on_intel do
      sha256 "999d93c8ffe3e5320a1d0e6d2d19b05a3a82ae335ea2f5557d099dae0e97808f"
      url "https://github.com/voska/frescatto/releases/download/v#{version}/frescatto_#{version}_linux_amd64.tar.gz",
        verified: "github.com/voska/frescatto"
    end
    on_arm do
      sha256 "1e9adb3fd4c4cbd255a212c50e570b227a170e3e811936c7c0fa5cf676757161"
      url "https://github.com/voska/frescatto/releases/download/v#{version}/frescatto_#{version}_linux_arm64.tar.gz",
        verified: "github.com/voska/frescatto"
    end
  end

  name "frescatto"
  desc "Frescatto fish & seafood CLI for humans and AI agents"
  homepage "https://github.com/voska/frescatto"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "frescatto"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/frescatto"]
    end
  end

  # No zap stanza required

end
