# This file was generated by GoReleaser. DO NOT EDIT.
cask "hn" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "de744ac9e5e27940e413a8ed0d65163724be0cb6ebc423dfc2abf33ab587985a"
      url "https://github.com/voska/hn-cli/releases/download/v#{version}/hn-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/voska/hn-cli"
    end
    on_arm do
      sha256 "9781762e2744a1bbe020a82a89bff7b3b23bda93981620eaa0b1e57f07056d33"
      url "https://github.com/voska/hn-cli/releases/download/v#{version}/hn-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/voska/hn-cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "7f4046653fca044c6ea793ed03003ecba5dd3bd180013020578a07a1a6f44753"
      url "https://github.com/voska/hn-cli/releases/download/v#{version}/hn-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/voska/hn-cli"
    end
    on_arm do
      sha256 "b4a5af2f5c1f5c3d8653b0befb176f771a15fd5bcad63fd33ee8925eaa68dc61"
      url "https://github.com/voska/hn-cli/releases/download/v#{version}/hn-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/voska/hn-cli"
    end
  end

  name "hn"
  desc "Agent-friendly Hacker News CLI via the Algolia API"
  homepage "https://github.com/voska/hn-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hn"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hn"]
    end
  end

  # No zap stanza required

end
