# This file was generated by GoReleaser. DO NOT EDIT.
cask "loby" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "3a9cba7aa22adac326caa437fa6c2cd364f817c746b1bb94ba47a12c7a90911f"
      url "https://github.com/voska/loby/releases/download/v#{version}/loby_#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/voska/loby"
    end
    on_arm do
      sha256 "3867728ad14baebf8faf847348a59050533599928352150ad028c493d5c0dcd1"
      url "https://github.com/voska/loby/releases/download/v#{version}/loby_#{version}_Darwin_arm64.tar.gz",
        verified: "github.com/voska/loby"
    end
  end

  on_linux do
    on_intel do
      sha256 "7ab92df90eae242aa3513e541afb1d1fa30640c8897e36adf4f2174d9acc78f6"
      url "https://github.com/voska/loby/releases/download/v#{version}/loby_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/voska/loby"
    end
    on_arm do
      sha256 "0696fc9bc055c32fb424b8b8d1f774cda7e478895470d3f197f954ad290b5cfe"
      url "https://github.com/voska/loby/releases/download/v#{version}/loby_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/voska/loby"
    end
  end

  name "loby"
  desc "Canonical CLI for Lob — direct mail, address verification, and campaigns for humans and AI agents."
  homepage "https://lobycli.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "loby"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/loby"]
    end
  end

  generate_completions_from_executable "loby",
    shell_parameter_format: :cobra

  # No zap stanza required

end
