# This file was generated by GoReleaser. DO NOT EDIT.
cask "loby" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "d6b4d6a384c91c43ab62d808a6cbb2a4789edffc6bcf33f25983da03115519c3"
      url "https://github.com/voska/loby/releases/download/v#{version}/loby_#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/voska/loby"
    end
    on_arm do
      sha256 "c0090f91703f70cb3bcdb69f32a5b310ac5c798fb6b0720401a52a8d27e84992"
      url "https://github.com/voska/loby/releases/download/v#{version}/loby_#{version}_Darwin_arm64.tar.gz",
        verified: "github.com/voska/loby"
    end
  end

  on_linux do
    on_intel do
      sha256 "143605ffc0fd7bfefacdf83fd60801753149d14325c240f909f8817f56c75467"
      url "https://github.com/voska/loby/releases/download/v#{version}/loby_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/voska/loby"
    end
    on_arm do
      sha256 "1f4f6fe14a9c6181334b72b698766fbd5bbc6a6e452cd73570c8c8f096a4e8c2"
      url "https://github.com/voska/loby/releases/download/v#{version}/loby_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/voska/loby"
    end
  end

  name "loby"
  desc "Canonical CLI for Lob — direct mail, address verification, and campaigns for humans and AI agents."
  homepage "https://lobycli.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "loby"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/loby"]
    end
  end
  generate_completions_from_executable "loby", "completion",
    shell_parameter_format: :cobra

  # No zap stanza required

end
