# This file was generated by GoReleaser. DO NOT EDIT.
cask "qbo" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "d19497b1a02a28b84cfb70859b49690704ae98738718090d093243074b2085c3"
      url "https://github.com/voska/qbo-cli/releases/download/v#{version}/qbo-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/voska/qbo-cli"
    end
    on_arm do
      sha256 "0190f0ed7976989ee9817007ff8b213cd139924c9313aad9381b771e5a29f763"
      url "https://github.com/voska/qbo-cli/releases/download/v#{version}/qbo-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/voska/qbo-cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "ff9dac579e5fd366d11219e052ddecbf8d19707b61a7032f24b87f0dd6ea953f"
      url "https://github.com/voska/qbo-cli/releases/download/v#{version}/qbo-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/voska/qbo-cli"
    end
    on_arm do
      sha256 "150e41534ef3ccc6da87a017a283913dc26886b7f3d1995f0de00bf41380cf32"
      url "https://github.com/voska/qbo-cli/releases/download/v#{version}/qbo-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/voska/qbo-cli"
    end
  end

  name "qbo"
  desc "QuickBooks Online CLI for humans and AI agents"
  homepage "https://github.com/voska/qbo-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qbo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qbo"]
    end
  end

  # No zap stanza required

end
