# This file was generated by GoReleaser. DO NOT EDIT.
cask "toktap" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "b3d65d88353939cb4e6207be7a45e11e1357e42220366b3a4300f7e0e7d56393"
      url "https://github.com/voska/toktap/releases/download/v#{version}/toktap_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/voska/toktap"
    end
    on_arm do
      sha256 "5dbac10e27bed22c46592cef3b0e620f01fce90eff50e2d3134f30bf4dd420b6"
      url "https://github.com/voska/toktap/releases/download/v#{version}/toktap_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/voska/toktap"
    end
  end

  on_linux do
    on_intel do
      sha256 "5741c567e6c9bfcd5970bf5131b59cbadee0ef5f114a95d2126e3417bd656369"
      url "https://github.com/voska/toktap/releases/download/v#{version}/toktap_#{version}_linux_amd64.tar.gz",
        verified: "github.com/voska/toktap"
    end
    on_arm do
      sha256 "57f223a6c13b0d00d12198b41d53125e6db1d21605bbca37f86ce3f5764b5066"
      url "https://github.com/voska/toktap/releases/download/v#{version}/toktap_#{version}_linux_arm64.tar.gz",
        verified: "github.com/voska/toktap"
    end
  end

  name "toktap"
  desc "Transparent proxy that taps LLM API traffic to extract token usage metrics"
  homepage "https://github.com/voska/toktap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toktap"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/toktap"]
    end
  end

  # No zap stanza required

end
