# This file was generated by GoReleaser. DO NOT EDIT.
cask "zonasul" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "8329062740e8f24a918cb464f75fff3aa787aca7839f37779ea9253b5eccddd2"
      url "https://github.com/voska/zonasul/releases/download/v#{version}/zonasul_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/voska/zonasul"
    end
    on_arm do
      sha256 "5b1a290097af8b842cf36178f5bd48f30c37d98c21740a5e92b21612ca9a6e23"
      url "https://github.com/voska/zonasul/releases/download/v#{version}/zonasul_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/voska/zonasul"
    end
  end

  on_linux do
    on_intel do
      sha256 "16809308b18161675ccd7493865f30c2d2bfb18877185a7e0f24e7939a54c805"
      url "https://github.com/voska/zonasul/releases/download/v#{version}/zonasul_#{version}_linux_amd64.tar.gz",
        verified: "github.com/voska/zonasul"
    end
    on_arm do
      sha256 "abfa2b589077342876e97e405cd23142ef80c3a64c47b0229d24fe185d651cc0"
      url "https://github.com/voska/zonasul/releases/download/v#{version}/zonasul_#{version}_linux_arm64.tar.gz",
        verified: "github.com/voska/zonasul"
    end
  end

  name "zonasul"
  desc "Zona Sul supermarket CLI for AI agents"
  homepage "https://github.com/voska/zonasul"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zonasul"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/zonasul"]
    end
  end

  # No zap stanza required

end
