# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Amadeus < Formula
  desc "Amadeus Travel API CLI for humans and AI agents"
  homepage "https://github.com/voska/amadeus-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/voska/amadeus-cli/releases/download/v0.1.0/amadeus_0.1.0_darwin_amd64.tar.gz"
      sha256 "1170ca93f78bdcce4bec2adb621aacee98be06e4713a83899810bf0a44711f82"

      define_method(:install) do
        bin.install "amadeus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/voska/amadeus-cli/releases/download/v0.1.0/amadeus_0.1.0_darwin_arm64.tar.gz"
      sha256 "0ea266af2fb6f36ad1829b9189e1d3369d0bf1c185b26a871dd8be609f57243f"

      define_method(:install) do
        bin.install "amadeus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/amadeus-cli/releases/download/v0.1.0/amadeus_0.1.0_linux_amd64.tar.gz"
      sha256 "2cc2e36d73dd38df7ef760807c74565c7a191d942bac763cd32d5c759139b690"
      define_method(:install) do
        bin.install "amadeus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/amadeus-cli/releases/download/v0.1.0/amadeus_0.1.0_linux_arm64.tar.gz"
      sha256 "96434fe7ce64b4f9149cb896c408b06d8b21f44de528a26064fbfd09a634dab1"
      define_method(:install) do
        bin.install "amadeus"
      end
    end
  end

  test do
    system "#{bin}/amadeus", "exit-codes", "--json"
  end
end
