# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Amadeus < Formula
  desc "Amadeus Travel API CLI for humans and AI agents"
  homepage "https://github.com/voska/amadeus-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/voska/amadeus-cli/releases/download/v0.2.0/amadeus_0.2.0_darwin_amd64.tar.gz"
      sha256 "a2dc2d96cedc98f755ccf875c23313e48d2a1b8a43b1b0f5f882b20e325dee05"

      define_method(:install) do
        bin.install "amadeus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/voska/amadeus-cli/releases/download/v0.2.0/amadeus_0.2.0_darwin_arm64.tar.gz"
      sha256 "6a976a60b853acf46eafece689980122e44a210d4056bbf2a253a4638c9ce628"

      define_method(:install) do
        bin.install "amadeus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/amadeus-cli/releases/download/v0.2.0/amadeus_0.2.0_linux_amd64.tar.gz"
      sha256 "cdfbdd49161145312df8b58fa18e4cbcdac551b6888e58373d494a8111ca2f20"
      define_method(:install) do
        bin.install "amadeus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/amadeus-cli/releases/download/v0.2.0/amadeus_0.2.0_linux_arm64.tar.gz"
      sha256 "181fa683d9c4d3197b3888cdbba75fa742c3f33b62f4d5cec8dd383b0754b7a4"
      define_method(:install) do
        bin.install "amadeus"
      end
    end
  end

  test do
    system "#{bin}/amadeus", "exit-codes", "--json"
  end
end
