# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Amadeus < Formula
  desc "Amadeus Travel API CLI for humans and AI agents"
  homepage "https://github.com/voska/amadeus-cli"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/voska/amadeus-cli/releases/download/v0.3.1/amadeus_0.3.1_darwin_amd64.tar.gz"
      sha256 "93cf83be8951f118fd27279969d01bb942d5b4f0242983839122ab7fdb7964bc"

      define_method(:install) do
        bin.install "amadeus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/voska/amadeus-cli/releases/download/v0.3.1/amadeus_0.3.1_darwin_arm64.tar.gz"
      sha256 "cd6963bf42213776404ccd1b50338c9eccddcbf00598bf7bc0d4c4d954cb3fac"

      define_method(:install) do
        bin.install "amadeus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/amadeus-cli/releases/download/v0.3.1/amadeus_0.3.1_linux_amd64.tar.gz"
      sha256 "e42f501ed9b47db9894bbb32faef028d76d7e16979d54548b7914f08ec387208"
      define_method(:install) do
        bin.install "amadeus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/amadeus-cli/releases/download/v0.3.1/amadeus_0.3.1_linux_arm64.tar.gz"
      sha256 "a7f324187bf335ac13084d2864fcad6fcafbde1813d8d6993c3e83ef4f9529bc"
      define_method(:install) do
        bin.install "amadeus"
      end
    end
  end

  test do
    system "#{bin}/amadeus", "exit-codes", "--json"
  end
end
