# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bambu < Formula
  desc "Slice, check, send and monitor Bambu Lab prints over LAN, for humans and AI agents"
  homepage "https://github.com/voska/bambu"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/voska/bambu/releases/download/v0.1.0/bambu_0.1.0_darwin_amd64.tar.gz"
      sha256 "7aaa150ab42c924dd124887a04f9bcdb38bbec2e05003d5a09ef69071ee432ec"

      define_method(:install) do
        bin.install "bambu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/voska/bambu/releases/download/v0.1.0/bambu_0.1.0_darwin_arm64.tar.gz"
      sha256 "eb06db78ab51de82b97b1d884cb4c888d274140b962b2599fb297287a33c4a51"

      define_method(:install) do
        bin.install "bambu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/bambu/releases/download/v0.1.0/bambu_0.1.0_linux_amd64.tar.gz"
      sha256 "82edd7534e36341e073e33cfca4efcba017540e7725cdb0f57df4fb55c1e4d8f"
      define_method(:install) do
        bin.install "bambu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/bambu/releases/download/v0.1.0/bambu_0.1.0_linux_arm64.tar.gz"
      sha256 "4781520b6b9c8db95a66ae226455c7894c17e637771460a9ba0bb4cdedea4b1c"
      define_method(:install) do
        bin.install "bambu"
      end
    end
  end

  test do
    system "#{bin}/bambu", "exit-codes", "--json"
  end
end
