# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bambu < Formula
  desc "Slice, check, send and monitor Bambu Lab prints over LAN, for humans and AI agents"
  homepage "https://github.com/voska/bambu"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/voska/bambu/releases/download/v0.2.0/bambu_0.2.0_darwin_amd64.tar.gz"
      sha256 "475568387d9bbcc95240a591c343b0460ceb73031cd2f2e691d89f69178bb184"

      define_method(:install) do
        bin.install "bambu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/voska/bambu/releases/download/v0.2.0/bambu_0.2.0_darwin_arm64.tar.gz"
      sha256 "94db804034351e867029753480df6ae0053f1aebcf6a123cba178540974a8117"

      define_method(:install) do
        bin.install "bambu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/bambu/releases/download/v0.2.0/bambu_0.2.0_linux_amd64.tar.gz"
      sha256 "04554ec0129aa7eab37fa128d3910c8c5b219c829b343d720fb82ddc5aa6ced9"
      define_method(:install) do
        bin.install "bambu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/bambu/releases/download/v0.2.0/bambu_0.2.0_linux_arm64.tar.gz"
      sha256 "49eef5ea90b28285e0c87250a42113ca88adfcac022362fef2f755916120c68d"
      define_method(:install) do
        bin.install "bambu"
      end
    end
  end

  test do
    system "#{bin}/bambu", "exit-codes", "--json"
  end
end
