# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Frescatto < Formula
  desc "Frescatto fish & seafood CLI for humans and AI agents"
  homepage "https://github.com/voska/frescatto"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/voska/frescatto/releases/download/v0.1.0/frescatto_0.1.0_darwin_amd64.tar.gz"
      sha256 "c15d23e588dc3752d5941ce96c023c7615dfe72e04305e14a242ec9b7e7620dd"

      define_method(:install) do
        bin.install "frescatto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/voska/frescatto/releases/download/v0.1.0/frescatto_0.1.0_darwin_arm64.tar.gz"
      sha256 "8752ccf350d8f72e37c9f6be821fa38a9edc2916065ea9403db88c1f1956ea02"

      define_method(:install) do
        bin.install "frescatto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/frescatto/releases/download/v0.1.0/frescatto_0.1.0_linux_amd64.tar.gz"
      sha256 "bd605134b5c44440389bd0aa09b79be8f9a75972590a6a4c5619e7dc5de4fafb"
      define_method(:install) do
        bin.install "frescatto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/frescatto/releases/download/v0.1.0/frescatto_0.1.0_linux_arm64.tar.gz"
      sha256 "344252f6a9b6fca43da88159954f9a8d232443b0bec2b29b6feef73ea163ff2e"
      define_method(:install) do
        bin.install "frescatto"
      end
    end
  end

  test do
    system "#{bin}/frescatto", "exit-codes", "--json"
  end
end
