# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hn < Formula
  desc "Agent-friendly Hacker News CLI via the Algolia API"
  homepage "https://github.com/voska/hn-cli"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/voska/hn-cli/releases/download/v0.2.1/hn-cli_0.2.1_darwin_amd64.tar.gz"
      sha256 "3fae823c465bd0c2acb6a5071a24aab6613f525b0174b8e31a0dea53964a896a"

      define_method(:install) do
        bin.install "hn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/voska/hn-cli/releases/download/v0.2.1/hn-cli_0.2.1_darwin_arm64.tar.gz"
      sha256 "4add3fd0105e3948243fa7ca00d0b2ca963437303cc49ac7ef95450579532854"

      define_method(:install) do
        bin.install "hn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/hn-cli/releases/download/v0.2.1/hn-cli_0.2.1_linux_amd64.tar.gz"
      sha256 "7389a9296ee5ca8bdd178810775d3ac4e3a2e53de6c3dc234e1b4eb50f27b3f8"
      define_method(:install) do
        bin.install "hn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/hn-cli/releases/download/v0.2.1/hn-cli_0.2.1_linux_arm64.tar.gz"
      sha256 "15e5ac36e5cf1ba745e3cf31f7503055bc4d6fb196d0b004cee1f752859b032b"
      define_method(:install) do
        bin.install "hn"
      end
    end
  end

  test do
    system "#{bin}/hn", "version"
  end
end
