# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hortifruti < Formula
  desc "Hortifruti greengrocer CLI for humans and AI agents"
  homepage "https://github.com/voska/hortifruti"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/voska/hortifruti/releases/download/v0.1.0/hortifruti_0.1.0_darwin_amd64.tar.gz"
      sha256 "7337e5ce512b3bfef2e2c635a7e6a06e88fcb181c9ca24c90976f944f1d9adec"

      define_method(:install) do
        bin.install "hortifruti"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/voska/hortifruti/releases/download/v0.1.0/hortifruti_0.1.0_darwin_arm64.tar.gz"
      sha256 "689acd1e24dae63a503efd2d5f5711ee2ac56d9d5d51da830aa92acaff544a1e"

      define_method(:install) do
        bin.install "hortifruti"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/hortifruti/releases/download/v0.1.0/hortifruti_0.1.0_linux_amd64.tar.gz"
      sha256 "d734e40f51e07592b6781159216b192e2259cbf88dc702187d413135691c3ef0"
      define_method(:install) do
        bin.install "hortifruti"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/hortifruti/releases/download/v0.1.0/hortifruti_0.1.0_linux_arm64.tar.gz"
      sha256 "0047449308524810e03a83802494c215c5c835ca5138973d6004d3f0da77a3df"
      define_method(:install) do
        bin.install "hortifruti"
      end
    end
  end

  test do
    system "#{bin}/hortifruti", "exit-codes", "--json"
  end
end
