# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hortifruti < Formula
  desc "Hortifruti greengrocer CLI for humans and AI agents"
  homepage "https://github.com/voska/hortifruti"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/voska/hortifruti/releases/download/v0.2.0/hortifruti_0.2.0_darwin_amd64.tar.gz"
      sha256 "b29b3d8c2468d3f31391ed5c03d822ebede34ed78046f48a7a3406f19d6c92d7"

      define_method(:install) do
        bin.install "hortifruti"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/voska/hortifruti/releases/download/v0.2.0/hortifruti_0.2.0_darwin_arm64.tar.gz"
      sha256 "29fa88cc648acc7663b22f30fed876e2582850118946239f04fbf3b3c8c9ae08"

      define_method(:install) do
        bin.install "hortifruti"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/hortifruti/releases/download/v0.2.0/hortifruti_0.2.0_linux_amd64.tar.gz"
      sha256 "ed5b71181ae3340aa07ec2e37778080ad1ad5e0df8a7b7ec88cdc0a1fed4d778"
      define_method(:install) do
        bin.install "hortifruti"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/hortifruti/releases/download/v0.2.0/hortifruti_0.2.0_linux_arm64.tar.gz"
      sha256 "aeb5959715fce7cc243727402b95724e54d94f18566bf639934749e34696014b"
      define_method(:install) do
        bin.install "hortifruti"
      end
    end
  end

  test do
    system "#{bin}/hortifruti", "exit-codes", "--json"
  end
end
