# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loby < Formula
  desc "Canonical CLI for Lob — direct mail, address verification, and campaigns for humans and AI agents."
  homepage "https://lobycli.com"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/voska/loby/releases/download/v0.3.2/loby_0.3.2_Darwin_x86_64.tar.gz"
      sha256 "a175065856091d395b613310208bcc18d63dd2b54c6bb4c194aedb78d9a21b3c"

      define_method(:install) do
        bin.install "loby"
        generate_completions_from_executable(bin/"loby", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/voska/loby/releases/download/v0.3.2/loby_0.3.2_Darwin_arm64.tar.gz"
      sha256 "2d4b6c7049fe64d791311433991abb162cdd835dbc386c3c3cb55ec716defd3f"

      define_method(:install) do
        bin.install "loby"
        generate_completions_from_executable(bin/"loby", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/loby/releases/download/v0.3.2/loby_0.3.2_Linux_x86_64.tar.gz"
      sha256 "844deb2ac4b1200dd7615a55b76684adab68a378d55e2b4e189ee7150430e475"
      define_method(:install) do
        bin.install "loby"
        generate_completions_from_executable(bin/"loby", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/loby/releases/download/v0.3.2/loby_0.3.2_Linux_arm64.tar.gz"
      sha256 "9c3f0ee658dc333d62e267ce8a85bc1205308ce14b43f99e0661364d742c573c"
      define_method(:install) do
        bin.install "loby"
        generate_completions_from_executable(bin/"loby", "completion")
      end
    end
  end

  test do
    assert_match "loby", shell_output("#{bin}/loby version")
  end
end
