# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loby < Formula
  desc "Canonical CLI for Lob — direct mail, address verification, and campaigns for humans and AI agents."
  homepage "https://lobycli.com"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/voska/loby/releases/download/v0.1.2/loby_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "357d17fe0bc2c9a3fa218cc20b3209890074b54914444c73265b61d3ac25b0a9"

      define_method(:install) do
        bin.install "loby"
        generate_completions_from_executable(bin/"loby", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/voska/loby/releases/download/v0.1.2/loby_0.1.2_Darwin_arm64.tar.gz"
      sha256 "bb6e0cf7ef8890be965d51471ddb0af5ffe80c469b262159d07312a97246871c"

      define_method(:install) do
        bin.install "loby"
        generate_completions_from_executable(bin/"loby", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/loby/releases/download/v0.1.2/loby_0.1.2_Linux_x86_64.tar.gz"
      sha256 "ade71950cb9e0c3a96c12018ea6b4292588fd9f8da3267e505a666dd146c49d6"
      define_method(:install) do
        bin.install "loby"
        generate_completions_from_executable(bin/"loby", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/loby/releases/download/v0.1.2/loby_0.1.2_Linux_arm64.tar.gz"
      sha256 "fc62978ef38db1e8324cbc9785ba57eebb4eb2f2f11f6593ce8b436d2dc1839e"
      define_method(:install) do
        bin.install "loby"
        generate_completions_from_executable(bin/"loby", "completion")
      end
    end
  end

  test do
    assert_match "loby", shell_output("#{bin}/loby version")
  end
end
