# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loby < Formula
  desc "Canonical CLI for Lob — direct mail, address verification, and campaigns for humans and AI agents."
  homepage "https://lobycli.com"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/voska/loby/releases/download/v0.2.0/loby_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "d7b2d3a11f43cd0ff7a70402b2de9bc36d020bc4f7800c3d46d5b90a7dc8affe"

      define_method(:install) do
        bin.install "loby"
        generate_completions_from_executable(bin/"loby", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/voska/loby/releases/download/v0.2.0/loby_0.2.0_Darwin_arm64.tar.gz"
      sha256 "8b105161e4a5367bbb26a0f38290bfc75f5ec010c0393e44bb542da2729aea20"

      define_method(:install) do
        bin.install "loby"
        generate_completions_from_executable(bin/"loby", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/loby/releases/download/v0.2.0/loby_0.2.0_Linux_x86_64.tar.gz"
      sha256 "835f3f1d1059e40b7e442f9a186691bfc5be7ce57b601085621e5017b0d51c5d"
      define_method(:install) do
        bin.install "loby"
        generate_completions_from_executable(bin/"loby", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/loby/releases/download/v0.2.0/loby_0.2.0_Linux_arm64.tar.gz"
      sha256 "4fab12445d0f3350dd248bdfdd3da87ecb18cabad7a405f8da718a16146a1f8a"
      define_method(:install) do
        bin.install "loby"
        generate_completions_from_executable(bin/"loby", "completion")
      end
    end
  end

  test do
    assert_match "loby", shell_output("#{bin}/loby version")
  end
end
