# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mantiqueira < Formula
  desc "Mantiqueira em Casa egg CLI for humans and AI agents"
  homepage "https://github.com/voska/mantiqueira"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/voska/mantiqueira/releases/download/v0.1.0/mantiqueira_0.1.0_darwin_amd64.tar.gz"
      sha256 "f525093bc1f8c58f25c09cdd4d3233ad5373e95696a2ac7c3fe7bc5231860450"

      define_method(:install) do
        bin.install "mantiqueira"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/voska/mantiqueira/releases/download/v0.1.0/mantiqueira_0.1.0_darwin_arm64.tar.gz"
      sha256 "a07b352dccc7320d642d3ebb775c4b7bf458c0668cb16508c9b7ada2f0435a34"

      define_method(:install) do
        bin.install "mantiqueira"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/mantiqueira/releases/download/v0.1.0/mantiqueira_0.1.0_linux_amd64.tar.gz"
      sha256 "e21c0432900475a707cf42cba94a3731a2ab872433a80e57253a64e9e578ebd3"
      define_method(:install) do
        bin.install "mantiqueira"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/mantiqueira/releases/download/v0.1.0/mantiqueira_0.1.0_linux_arm64.tar.gz"
      sha256 "ebf391f3d678fde21ffb677eb2bcfc87a6b915bd4e487f7a93eba2304bcbb1f4"
      define_method(:install) do
        bin.install "mantiqueira"
      end
    end
  end

  test do
    system "#{bin}/mantiqueira", "exit-codes", "--json"
  end
end
