# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mantiqueira < Formula
  desc "Mantiqueira em Casa egg CLI for humans and AI agents"
  homepage "https://github.com/voska/mantiqueira"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/voska/mantiqueira/releases/download/v0.2.0/mantiqueira_0.2.0_darwin_amd64.tar.gz"
      sha256 "f26fa1a32e07a8c4d69a60f0893bdfb0386438b25da859753101839b0da0ec81"

      define_method(:install) do
        bin.install "mantiqueira"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/voska/mantiqueira/releases/download/v0.2.0/mantiqueira_0.2.0_darwin_arm64.tar.gz"
      sha256 "e026b48d72998b8edc5512eeb67132fc825cd91fe77d5b42b186fd4d4c94edc2"

      define_method(:install) do
        bin.install "mantiqueira"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/mantiqueira/releases/download/v0.2.0/mantiqueira_0.2.0_linux_amd64.tar.gz"
      sha256 "4073ab27451b560f7c519efd76e87e0215bb8690f56d587c72d395d62777bb58"
      define_method(:install) do
        bin.install "mantiqueira"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/mantiqueira/releases/download/v0.2.0/mantiqueira_0.2.0_linux_arm64.tar.gz"
      sha256 "9e37706874b4cb67eb4a08d348fb7c127bec73da1f754c31d02c4188b2ebe119"
      define_method(:install) do
        bin.install "mantiqueira"
      end
    end
  end

  test do
    system "#{bin}/mantiqueira", "exit-codes", "--json"
  end
end
