# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prezunic < Formula
  desc "Prezunic supermarket CLI for humans and AI agents"
  homepage "https://github.com/voska/prezunic"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/voska/prezunic/releases/download/v0.2.0/prezunic_0.2.0_darwin_amd64.tar.gz"
      sha256 "07be68e4e5fd9474107be116ba9ef4cf3c38ab165f555c06053fb6ce5840be87"

      define_method(:install) do
        bin.install "prezunic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/voska/prezunic/releases/download/v0.2.0/prezunic_0.2.0_darwin_arm64.tar.gz"
      sha256 "fc5c6d32dc084b739d6bf20b6d53f24cd97207b5f6fc93e83270ba8b1694753c"

      define_method(:install) do
        bin.install "prezunic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/prezunic/releases/download/v0.2.0/prezunic_0.2.0_linux_amd64.tar.gz"
      sha256 "5864fa5b2983df320f8b846c8002db865e0eae4589330f9ab4f6dba05e3da4e4"
      define_method(:install) do
        bin.install "prezunic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/prezunic/releases/download/v0.2.0/prezunic_0.2.0_linux_arm64.tar.gz"
      sha256 "ca4916393c688546f4da2aea2311fd485a6c2aae20bf610cf2d2cbda3576673b"
      define_method(:install) do
        bin.install "prezunic"
      end
    end
  end

  test do
    system "#{bin}/prezunic", "exit-codes", "--json"
  end
end
