# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prezunic < Formula
  desc "Prezunic supermarket CLI for humans and AI agents"
  homepage "https://github.com/voska/prezunic"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/voska/prezunic/releases/download/v0.1.0/prezunic_0.1.0_darwin_amd64.tar.gz"
      sha256 "02fe7857250a4df69a5390d875845e48dfbe37a9db9694894e2ab7449d83135d"

      define_method(:install) do
        bin.install "prezunic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/voska/prezunic/releases/download/v0.1.0/prezunic_0.1.0_darwin_arm64.tar.gz"
      sha256 "d0a1a9a2822035578c6f55dd5520d35e0ba9b51d99bce477d299f8b674bd5008"

      define_method(:install) do
        bin.install "prezunic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/prezunic/releases/download/v0.1.0/prezunic_0.1.0_linux_amd64.tar.gz"
      sha256 "04da3ed44d69478cae6b1752048ef0bcda476c0a71bde3347cc69104a551370a"
      define_method(:install) do
        bin.install "prezunic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/prezunic/releases/download/v0.1.0/prezunic_0.1.0_linux_arm64.tar.gz"
      sha256 "2b4bff37c5c0c05a4fd71568e49aae7f817adfb0dab4b2e9d34fb0aa824a5b0d"
      define_method(:install) do
        bin.install "prezunic"
      end
    end
  end

  test do
    system "#{bin}/prezunic", "exit-codes", "--json"
  end
end
