# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qbo < Formula
  desc "QuickBooks Online CLI for humans and AI agents"
  homepage "https://github.com/voska/qbo-cli"
  version "0.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/voska/qbo-cli/releases/download/v0.6.1/qbo-cli_0.6.1_darwin_amd64.tar.gz"
      sha256 "e72b85353f88636f2c66ba282879978be99c01019e9a357db4a1059199386dff"

      define_method(:install) do
        bin.install "qbo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/voska/qbo-cli/releases/download/v0.6.1/qbo-cli_0.6.1_darwin_arm64.tar.gz"
      sha256 "f5911ba3b1f1f432a9c6efb4597ee886b699ee0ee71d132ff8e2074472ff1010"

      define_method(:install) do
        bin.install "qbo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/qbo-cli/releases/download/v0.6.1/qbo-cli_0.6.1_linux_amd64.tar.gz"
      sha256 "ce7774c7c641b1c6fe356e2e522465fbf16d80bce0a87fd2c8027774e2a46f31"
      define_method(:install) do
        bin.install "qbo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/qbo-cli/releases/download/v0.6.1/qbo-cli_0.6.1_linux_arm64.tar.gz"
      sha256 "150cdb50c2dacc8c990c3594b358dcd84f2336de31cad73de266bbdf32b3d4e0"
      define_method(:install) do
        bin.install "qbo"
      end
    end
  end

  test do
    system "#{bin}/qbo", "exit-codes", "--json"
  end
end
