# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qbo < Formula
  desc "QuickBooks Online CLI for humans and AI agents"
  homepage "https://github.com/voska/qbo-cli"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/voska/qbo-cli/releases/download/v0.5.0/qbo-cli_0.5.0_darwin_amd64.tar.gz"
      sha256 "fefa2525c81e5b052947f229678486e2f497c5c03e18d652744c135a1412b658"

      define_method(:install) do
        bin.install "qbo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/voska/qbo-cli/releases/download/v0.5.0/qbo-cli_0.5.0_darwin_arm64.tar.gz"
      sha256 "2a464c1eee2ee4da8a9790cd972bd96991617fd074f302e7a973fd706aa87357"

      define_method(:install) do
        bin.install "qbo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/qbo-cli/releases/download/v0.5.0/qbo-cli_0.5.0_linux_amd64.tar.gz"
      sha256 "c311cec496be7ec60e48ecf9fb31e79c9df70b6d8355449f2719975f595bc71b"
      define_method(:install) do
        bin.install "qbo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/qbo-cli/releases/download/v0.5.0/qbo-cli_0.5.0_linux_arm64.tar.gz"
      sha256 "7d60f1d25cfa4cbe01f91a3f54b585382a75c5eaf52e132989c8bc514366635b"
      define_method(:install) do
        bin.install "qbo"
      end
    end
  end

  test do
    system "#{bin}/qbo", "exit-codes", "--json"
  end
end
