# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toktap < Formula
  desc "Transparent proxy that taps LLM API traffic to extract token usage metrics"
  homepage "https://github.com/voska/toktap"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/voska/toktap/releases/download/v0.5.1/toktap_0.5.1_darwin_amd64.tar.gz"
      sha256 "68a71ed90f66d044b572aa4ddd6b2a93d4d07edad0dbcfbbbc3751953e9aa9c5"

      define_method(:install) do
        bin.install "toktap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/voska/toktap/releases/download/v0.5.1/toktap_0.5.1_darwin_arm64.tar.gz"
      sha256 "e9a094a60852bfd0e6ecb0c93ad028529a77eda7011d13592170b2d0774806ed"

      define_method(:install) do
        bin.install "toktap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/toktap/releases/download/v0.5.1/toktap_0.5.1_linux_amd64.tar.gz"
      sha256 "455cc9c6919ab0a1210686ee5a0468fb9e14c04dbe079a0236a6381535e0dd54"
      define_method(:install) do
        bin.install "toktap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/toktap/releases/download/v0.5.1/toktap_0.5.1_linux_arm64.tar.gz"
      sha256 "80e25ba1c1557c79d8e5c786f5e7ad027e35e872bec8e2d9b1c3fafc795f8163"
      define_method(:install) do
        bin.install "toktap"
      end
    end
  end

  test do
    system "#{bin}/toktap", "--version"
  end
end
