# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toktap < Formula
  desc "Transparent proxy that taps LLM API traffic to extract token usage metrics"
  homepage "https://github.com/voska/toktap"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/voska/toktap/releases/download/v0.4.0/toktap_0.4.0_darwin_amd64.tar.gz"
      sha256 "a7b5bfe50b7b295376e14b0e77a3def555a6394ac559d9db0255d0772fba06e3"

      define_method(:install) do
        bin.install "toktap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/voska/toktap/releases/download/v0.4.0/toktap_0.4.0_darwin_arm64.tar.gz"
      sha256 "63f3762768d7b7913995e8a6628d5b95439a59c2af4d14cd3543ef948972d49e"

      define_method(:install) do
        bin.install "toktap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/toktap/releases/download/v0.4.0/toktap_0.4.0_linux_amd64.tar.gz"
      sha256 "faee34564f090926b6d9eb766f6a49951e2b2b23e27d558d8296d8d5a1350e13"
      define_method(:install) do
        bin.install "toktap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/toktap/releases/download/v0.4.0/toktap_0.4.0_linux_arm64.tar.gz"
      sha256 "0f7d3b58c8dcb815fa4c19c17515f6c67f4de337bfc649bbb0ae92285054b225"
      define_method(:install) do
        bin.install "toktap"
      end
    end
  end

  test do
    system "#{bin}/toktap", "--version"
  end
end
