# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Venancio < Formula
  desc "Drogaria Venancio pharmacy CLI for humans and AI agents"
  homepage "https://github.com/voska/venancio"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/voska/venancio/releases/download/v0.1.0/venancio_0.1.0_darwin_amd64.tar.gz"
      sha256 "c27646e64cca03540fe6ce04831a1e8489a9ec08a9c79c1a55f7fc041f8d21c8"

      define_method(:install) do
        bin.install "venancio"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/voska/venancio/releases/download/v0.1.0/venancio_0.1.0_darwin_arm64.tar.gz"
      sha256 "31acae1b15f828606f97008fff9cb9122eab75c74e4e162937c23888a41de454"

      define_method(:install) do
        bin.install "venancio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/venancio/releases/download/v0.1.0/venancio_0.1.0_linux_amd64.tar.gz"
      sha256 "a30d8287c25534fab4d08a6d2d1d8fc14b295b6dc56d2daf7546c5345f2e2941"
      define_method(:install) do
        bin.install "venancio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/venancio/releases/download/v0.1.0/venancio_0.1.0_linux_arm64.tar.gz"
      sha256 "27dfeb95dcb26bf86fb0ff40df027f3d48b5b3f6d8e7b305c45371143b335405"
      define_method(:install) do
        bin.install "venancio"
      end
    end
  end

  test do
    system "#{bin}/venancio", "exit-codes", "--json"
  end
end
