# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zonasul < Formula
  desc "Zona Sul supermarket CLI for AI agents"
  homepage "https://github.com/voska/zonasul"
  version "0.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/voska/zonasul/releases/download/v0.7.1/zonasul_0.7.1_darwin_amd64.tar.gz"
      sha256 "04928f9c9115462d5f057ce0653968161e2afffd5baa0d8156661c80a9167f89"

      define_method(:install) do
        bin.install "zonasul"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/voska/zonasul/releases/download/v0.7.1/zonasul_0.7.1_darwin_arm64.tar.gz"
      sha256 "9683fdcbe55b3d33b254fc68909046f0faf462669595dcf1723ee8219c0026d1"

      define_method(:install) do
        bin.install "zonasul"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/zonasul/releases/download/v0.7.1/zonasul_0.7.1_linux_amd64.tar.gz"
      sha256 "7b871f9c28d94d1c62cb191ad9bb41016710d009a29e22715536019a83b57906"
      define_method(:install) do
        bin.install "zonasul"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/zonasul/releases/download/v0.7.1/zonasul_0.7.1_linux_arm64.tar.gz"
      sha256 "aac3f1ba47b821734f48a4a51d85a7dcb743ce2d05c76891c12f84d4e15cf735"
      define_method(:install) do
        bin.install "zonasul"
      end
    end
  end

  test do
    system "#{bin}/zonasul", "agent", "exit-codes", "--json"
  end
end
