# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zonasul < Formula
  desc "Zona Sul supermarket CLI for AI agents"
  homepage "https://github.com/voska/zonasul"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/voska/zonasul/releases/download/v0.8.0/zonasul_0.8.0_darwin_amd64.tar.gz"
      sha256 "da41758cfedf192d0844a6c0ff33c5f0813eee70a48113ee3edcf910a6a8349f"

      define_method(:install) do
        bin.install "zonasul"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/voska/zonasul/releases/download/v0.8.0/zonasul_0.8.0_darwin_arm64.tar.gz"
      sha256 "98715362c1bb921f53ec1e82161372d04beea07f1e4cec31f1cfa490f5a594c4"

      define_method(:install) do
        bin.install "zonasul"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/zonasul/releases/download/v0.8.0/zonasul_0.8.0_linux_amd64.tar.gz"
      sha256 "1dcb65cd5ac3de03a2fc302e8576d4e1e70b5501a216e6e2a97d99a4377b150f"
      define_method(:install) do
        bin.install "zonasul"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voska/zonasul/releases/download/v0.8.0/zonasul_0.8.0_linux_arm64.tar.gz"
      sha256 "fd584b69dc8f57c827274718116f1cb0c5fa8129c99e8eb85c3e638d9bf9314d"
      define_method(:install) do
        bin.install "zonasul"
      end
    end
  end

  test do
    system "#{bin}/zonasul", "agent", "exit-codes", "--json"
  end
end
